// Code generated by ogen, DO NOT EDIT.
package order_v1

type GetOrderByUuidRes interface {
	getOrderByUuidRes()
}

type OrderCancelByUuidRes interface {
	orderCancelByUuidRes()
}

type OrderPayRes interface {
	orderPayRes()
}
